# 应用名称
spring:
  application:
    name: springboot-mybatis-quickstart
  # 数据库数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/db01
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

# MyBatis 全局配置
mybatis:
  configuration:
    # 开启下划线转驼峰
    map-underscore-to-camel-case: true
    # 打印SQL日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl